# Show don't tell 

version 0

Will be more organised with the next versions

In [1]:
import numpy as np

### 1- literal_eval

In [2]:
from ast import literal_eval
literal_eval("['sadad','sadsad']")

['sadad', 'sadsad']

In [3]:
l=literal_eval("['sadad','sadsad']")
type(l)

list

In [4]:
l[0]

'sadad'

### 2- Sorting dictionary

In [5]:
example={"a":2,"b":1,"c":3}
sorted(example.items(), key=lambda x: x[1], reverse=True)

[('c', 3), ('a', 2), ('b', 1)]

In [6]:
example={"a":(3,2),"b":(5,1),"c":(0,3)}
sorted(example.items(), key=lambda x: x[1][1], reverse=True)

[('c', (0, 3)), ('a', (3, 2)), ('b', (5, 1))]

### argsort

In [7]:
arr=np.array([1,3,5,4,6,2])
arr.argsort()

array([0, 5, 1, 3, 2, 4])

### 3- reversed index

In [8]:
example={"a":2,"b":1,"c":3}
reversed_vocab = {i:word for word,i in example.items()}
reversed_vocab

{1: 'b', 2: 'a', 3: 'c'}

### 4- Encoding

In [9]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer(classes=np.array(['c1','c2','c3','c4']))#classes=classes.keys())
mlb.classes

array(['c1', 'c2', 'c3', 'c4'], dtype='<U2')

In [10]:
transformed=mlb.fit_transform([['c2','c4'],
                         ['c1','c2'],
                         ['c2','c3'],['c4']])
print(transformed)
mlb.classes_

[[0 1 0 1]
 [1 1 0 0]
 [0 1 1 0]
 [0 0 0 1]]


array(['c1', 'c2', 'c3', 'c4'], dtype=object)

In [11]:
mlb.inverse_transform(transformed)

[('c2', 'c4'), ('c1', 'c2'), ('c2', 'c3'), ('c4',)]

### 5- Evaluation metrics

In [12]:
from sklearn.metrics import roc_auc_score 
from sklearn.metrics import average_precision_score
from sklearn.metrics import recall_score

#### 1. Accuracy
In multilabel classification, this function computes subset accuracy: the set of labels predicted for a sample must exactly match the corresponding set of labels in y_true.

In [13]:
from sklearn.metrics import accuracy_score
accuracy_score(np.array([[0, 1], [1, 1]]), np.ones((2, 2)))

0.5

#### 2. F1_score

p_micro*re_micro/(p_micro+re_micro)

In [14]:
from sklearn.metrics import f1_score
y_true = [0, 1, 2, 0, 1, 2]
y_pred = [0, 2, 1, 0, 0, 1]
f1_score(y_true, y_pred, average='macro')  

0.26666666666666666

In [15]:
f1_score(y_true, y_pred, average='micro')  

0.3333333333333333

In [16]:
f1_score(y_true, y_pred, average='weighted')  

0.26666666666666666

In [17]:
f1_score(y_true, y_pred, average=None)

array([0.8, 0. , 0. ])

In [18]:
p0=1/1.
p1=0/2.
p2=0/2.
p_macro=(p0+p1+p2)/3.
p_micro=2/6.
p_macro,p_micro

(0.3333333333333333, 0.3333333333333333)

In [19]:
re0=2./3.
re1=0
re2=0
re_macro=(re0+re1+re2)/3.
re_micro=2./6.
re_macro,re_micro

(0.2222222222222222, 0.3333333333333333)

In [20]:
f1_macro=2*p_macro*re_macro/(p_macro+re_macro)
f1_micro=2*p_micro*re_micro/(p_micro+re_micro)
f1_macro,f1_micro

(0.26666666666666666, 0.3333333333333333)

### 6- Extend

In [21]:
s=[]
s.extend([1,2,3,[3,4]])
s.extend([1,2,3,[3,4]])
s

[1, 2, 3, [3, 4], 1, 2, 3, [3, 4]]

## sp_sparse 

<a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html#scipy.sparse.csr_matrix">sparse doc</a>

### 1. csr_matrix


In [23]:
from scipy import sparse as sp_sparse

In [24]:
arr=np.zeros((10,10))
for i in range(10):
    arr[i,i]=i+1
    arr[10-i-1,i]=i//2+1
arr

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  5.],
       [ 0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  3.,  0.,  0.,  0.,  0.,  4.,  0.,  0.],
       [ 0.,  0.,  0.,  4.,  0.,  0.,  4.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  5.,  3.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  3.,  6.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  0.,  0.,  7.,  0.,  0.,  0.],
       [ 0.,  0.,  2.,  0.,  0.,  0.,  0.,  8.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  9.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]])

In [25]:
sp_arr=sp_sparse.csr_matrix(arr)
sp_arr.data

array([ 1.,  5.,  2.,  5.,  3.,  4.,  4.,  4.,  5.,  3.,  3.,  6.,  2.,
        7.,  2.,  8.,  1.,  9.,  1., 10.])

In [26]:
sp_arr.getrow(0).toarray()

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 5.]])

### 2. vstack

In [27]:
>>> print(sp_arr.toarray())

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  5.]
 [ 0.  2.  0.  0.  0.  0.  0.  0.  5.  0.]
 [ 0.  0.  3.  0.  0.  0.  0.  4.  0.  0.]
 [ 0.  0.  0.  4.  0.  0.  4.  0.  0.  0.]
 [ 0.  0.  0.  0.  5.  3.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  3.  6.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0.  0.  7.  0.  0.  0.]
 [ 0.  0.  2.  0.  0.  0.  0.  8.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  9.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0. 10.]]


In [28]:
>>> print(sp_sparse.vstack([sp_arr,sp_arr]).toarray())

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  5.]
 [ 0.  2.  0.  0.  0.  0.  0.  0.  5.  0.]
 [ 0.  0.  3.  0.  0.  0.  0.  4.  0.  0.]
 [ 0.  0.  0.  4.  0.  0.  4.  0.  0.  0.]
 [ 0.  0.  0.  0.  5.  3.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  3.  6.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0.  0.  7.  0.  0.  0.]
 [ 0.  0.  2.  0.  0.  0.  0.  8.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  9.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0. 10.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  5.]
 [ 0.  2.  0.  0.  0.  0.  0.  0.  5.  0.]
 [ 0.  0.  3.  0.  0.  0.  0.  4.  0.  0.]
 [ 0.  0.  0.  4.  0.  0.  4.  0.  0.  0.]
 [ 0.  0.  0.  0.  5.  3.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  3.  6.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0.  0.  7.  0.  0.  0.]
 [ 0.  0.  2.  0.  0.  0.  0.  8.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  9.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0. 10.]]
